python run.py experiments/iv_generalization.py mp.n_procs=1 env.action_dim=2 wandb.dryrun=False wandb.project=iv-test wandb.group=with-im-home-7 wandb.name=with-im-home-7-0.0 ppo.alpha=0.0 ppo.lr=0.001 icm.lr=0.001 main.n_steps=35000 main.with_im=True&
python run.py experiments/iv_generalization.py mp.n_procs=1 env.action_dim=2 wandb.dryrun=False wandb.project=iv-test wandb.group=with-im-home-7 wandb.name=with-im-home-7-0.05 ppo.alpha=0.05 ppo.lr=0.001 icm.lr=0.001 main.n_steps=35000 main.with_im=True&
python run.py experiments/iv_generalization.py mp.n_procs=1 env.action_dim=2 wandb.dryrun=False wandb.project=iv-test wandb.group=with-im-home-7 wandb.name=with-im-home-7-0.1 ppo.alpha=0.1 ppo.lr=0.001 icm.lr=0.001 main.n_steps=35000 main.with_im=True&
python run.py experiments/iv_generalization.py mp.n_procs=1 env.action_dim=2 wandb.dryrun=False wandb.project=iv-test wandb.group=with-im-home-7 wandb.name=with-im-home-7-0.2 ppo.alpha=0.2 ppo.lr=0.001 icm.lr=0.001 main.n_steps=35000 main.with_im=True&
python run.py experiments/iv_generalization.py mp.n_procs=1 env.action_dim=2 wandb.dryrun=False wandb.project=iv-test wandb.group=with-im-home-7 wandb.name=with-im-home-7-0.3 ppo.alpha=0.3 ppo.lr=0.001 icm.lr=0.001 main.n_steps=35000 main.with_im=True&

python run.py experiments/iv_generalization.py mp.n_procs=1 env.action_dim=2 wandb.dryrun=False wandb.project=iv-test wandb.group=without-im-home-7 wandb.name=without-im-home-7-0.0 ppo.alpha=0.0 ppo.lr=0.001 icm.lr=0.001 main.n_steps=35000 main.with_im=False&
python run.py experiments/iv_generalization.py mp.n_procs=1 env.action_dim=2 wandb.dryrun=False wandb.project=iv-test wandb.group=without-im-home-7 wandb.name=without-im-home-7-0.05 ppo.alpha=0.05 ppo.lr=0.001 icm.lr=0.001 main.n_steps=35000 main.with_im=False&
python run.py experiments/iv_generalization.py mp.n_procs=1 env.action_dim=2 wandb.dryrun=False wandb.project=iv-test wandb.group=without-im-home-7 wandb.name=without-im-home-7-0.1 ppo.alpha=0.1 ppo.lr=0.001 icm.lr=0.001 main.n_steps=35000 main.with_im=False&
python run.py experiments/iv_generalization.py mp.n_procs=1 env.action_dim=2 wandb.dryrun=False wandb.project=iv-test wandb.group=without-im-home-7 wandb.name=without-im-home-7-0.2 ppo.alpha=0.2 ppo.lr=0.001 icm.lr=0.001 main.n_steps=35000 main.with_im=False&
python run.py experiments/iv_generalization.py mp.n_procs=1 env.action_dim=2 wandb.dryrun=False wandb.project=iv-test wandb.group=without-im-home-7 wandb.name=without-im-home-7-0.3 ppo.alpha=0.3 ppo.lr=0.001 icm.lr=0.001 main.n_steps=35000 main.with_im=False&